image: registry.gitlab.com/pages/hugo:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  script:
  - gulp build:dev && gulp hugo:dev
  except:
  - master

pages:
  script:
  - npm install -g gulp
  - npm install
  - gulp build:prod && gulp hugo:prod
  artifacts:
    paths:
    - public
  only:
  - master
