baseurl = "/"
languageCode = "en-us"
title = "daSWAG | Serverless Web Applicaiton Generator"
theme = "daswag"
metadataformat = "yaml"
canonifyurls = true
enableGitInfo = true
publishDir = "public"

# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "daswag.tech"
	description = "Open Source Serverless Generator for creating Web application projects in seconds!"
	copyright = "Released under the Apache 2 license"

	# Repository
	provider = "Gitlab"
	repo_url = "https://gitlab.com/daswag"

	version = "0.0.1"
	logo = "images/favicon.png?v=1.0"
	favicon = "images/favicon.png?v=1.0"

	permalink = "#"

	# Custom assets
	custom_css  = [
	  "stylesheets/dropdown.css"
	]
	custom_js   = [
	  "javascripts/lunr.min.js",
	  "javascripts/version.js"
	]

	versionedDocs = [
	    "How daSWAG works",
	    "Installation"
	]

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "pink"
    	accent  = "pink"

    [params.font]
    	text = "Roboto"
    	code = "Roboto Mono"

[social]
	twitter = "daswag_project"
	gitlab  = "daswag/daswag-website"

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true

[taxonomies]
  platform = "platforms"
  serie = "series"

# Top nav

[[menu.topnav]]
	name   = "Documentation"
    identifier = "developers-top"
	url    = "/documentation/"
	weight = 10

# Main categories

[[menu.main]]
	name   = "Documentation"
	url    = "/documentation/"
	weight = 20

[[menu.main]]
	name   = "About"
	url    = "/about/"
	weight = 30

[[menu.main]]
	name   = "News"
	url    = "/news/"
	weight = 40

[[menu.main]]
	name	= "How daSWAG works"
	url = "/documentation/how-daswag-works/"
	parent = "Documentation"
	weight = 10

[[menu.main]]
	name = "Installation"
	identifier = "Installation"
	url = "/documentation/installation/overview/"
	parent = "Documentation"
	weight = 30

[[menu.main]]
	name = "Companies using daSWAG"
	url = "/documentation/companies-using-daswag"
	parent = "Documentation"
	weight = 20
